"""The published artifacts the calculation may read, and nothing else.

Phase 1 decided what a user may ask. This module decides what the answer may be
computed from, and the two are separate trust problems. A scenario document is
untrusted because a person wrote it; these four files are trusted because they were
published, reviewed and pinned — which is only true for as long as something checks
that the bytes on disk are still the bytes that were pinned.

**The set is closed and named.** Four artifacts, each declared individually in
``configs/structural_exposure_scenario.yaml`` with its own path and digest. No
directory scan, no glob, no "load whatever is in docs/". A tool that discovers its own
inputs is a tool whose inputs can change without anybody deciding they should.

**The pins are the scenario's own.** ``docs/e2r1_release_manifest.json`` is a frozen
record of one publication; reading it at runtime would make an immutable historical
document into a live registry, and a future release row would quietly become a runtime
dependency. The two agree today, and a test checks that they agree — a different and
safer relationship than depending on one.

**Digests are canonical, not raw.** Two of the four files are stored LF in Git and
checked out CRLF on Windows. A raw-byte pin would verify on one platform and fail on
the other for a file nobody had edited, which is precisely the defect Task CI-R1 was
created to fix. Every pin here is
:func:`~thai_supply_chain_ews.release.byte_provenance.canonical_digest`, and the
representation is declared beside the value rather than assumed.

**C3 is authoritative; C5 is corroboration.** The exposure matrix supplies every
coefficient, sign and eligibility flag the arithmetic uses. The two C5 documents supply
mediator attribution and price-stage metadata, and their own copies of the coefficients
are checked for agreement within a declared tolerance but never scored. They were
generated by separate float64 runs and differ in the last digit or two for fourteen of
the forty-eight pairs; requiring exact equality would fail on arithmetic noise, and
ignoring the comparison entirely would let a genuinely different artifact through.

Nothing here reaches the network, writes a file, repairs an artifact, or falls back to
an unpinned copy of anything.
"""

from __future__ import annotations

import csv
import io
import json
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path

import yaml

from thai_supply_chain_ews.release.byte_provenance import (
    CANONICAL_LF,
    RAW_BYTES,
    canonical_digest,
    digest,
)
from thai_supply_chain_ews.scenario.contract import (
    DEFAULT_POLICY_PATH,
    REGISTERED_CHANNELS,
    ScenarioPolicy,
    ScenarioPolicyError,
    _PolicyLoader,
    load_policy,
)

__all__ = [
    "ARTIFACT_NAMES",
    "EXPECTED_INDUSTRY_COUNT",
    "EXPECTED_MEDIATORS_PER_PAIR",
    "EXPECTED_PAIR_COUNT",
    "SUPPORTED_DIGEST_REPRESENTATIONS",
    "ArtifactBundle",
    "ArtifactDeclaration",
    "ArtifactIntegrityError",
    "ExposurePair",
    "Industry",
    "Mediator",
    "PriceStage",
    "load_artifact_bundle",
    "read_artifact_declarations",
]

#: The four logical artifacts, in the order the policy declares them.
ARTIFACT_NAMES = (
    "exposure_matrix",
    "structural_path_audit",
    "price_stage_source_audit",
    "industry_map",
)

#: Representations a declaration may name. Anything else is refused rather than
#: guessed: an unrecognised representation means the pin's meaning is unknown, and a
#: digest whose meaning is unknown verifies nothing.
SUPPORTED_DIGEST_REPRESENTATIONS = frozenset({CANONICAL_LF, RAW_BYTES})

EXPECTED_INDUSTRY_COUNT = 12
EXPECTED_PAIR_COUNT = 48
EXPECTED_MEDIATORS_PER_PAIR = 10


class ArtifactIntegrityError(RuntimeError):
    """A published artifact is missing, altered, unreadable or internally wrong.

    A sibling of :class:`~thai_supply_chain_ews.scenario.contract.ScenarioPolicyError`
    rather than of the contract errors, and for the same reason: this is never the
    user's fault and cannot be fixed by editing a scenario. It is a shipped-artifact
    integrity failure, and the future command-line layer maps both onto one exit code.
    """


@dataclass(frozen=True)
class ArtifactDeclaration:
    """One pinned artifact, exactly as the policy declares it."""

    name: str
    path: str
    fmt: str
    sha256: str
    digest_representation: str
    role: str

    def digest_of(self, data: bytes) -> str:
        if self.digest_representation == CANONICAL_LF:
            return canonical_digest(data)
        return digest(data)


@dataclass(frozen=True)
class Industry:
    """One project industry, from ``data/mapping/industry_map.csv``."""

    industry_id: str
    name_en: str
    tsic_divisions: tuple[str, ...]
    status: str


@dataclass(frozen=True)
class Mediator:
    """One ``commodity -> intermediate sector -> industry`` attribution row."""

    industry_id: str
    channel: str
    rank: int
    intermediate_sector_code: str
    intermediate_sector_label: str
    contribution: Decimal
    share_of_indirect: Decimal
    cumulative_share: Decimal
    pair_direct_exposure: Decimal
    pair_total_exposure: Decimal


@dataclass(frozen=True)
class PriceStage:
    """Price-stage alignment metadata for one industry/channel pair."""

    industry_id: str
    channel: str
    price_stage: str
    alignment_status: str
    mapped_io_sector_code: str
    limitations: str
    shared_source_sector_warning: str | None
    pair_direct_exposure: Decimal
    pair_total_exposure: Decimal


@dataclass(frozen=True)
class ExposurePair:
    """One industry/channel pair, as published.

    ``propagated_exposure`` is **derived** as ``total - direct`` rather than read from
    the published ``indirect_exposure``. The artifact's three coefficients were written
    by float64 arithmetic and do not satisfy ``direct + indirect == total`` exactly —
    they disagree by up to 6e-17. Deriving the component makes the identity true by
    construction instead of nearly true by luck. The published field is kept beside it,
    unaltered, because it is what the artifact says.
    """

    industry_id: str
    industry_name: str
    channel: str
    io_sector_code: str
    direct_exposure: Decimal
    total_requirement_exposure: Decimal
    published_indirect_exposure: Decimal
    sign: int | None
    direction_channel: str
    feature_eligible: bool
    proxy_fit_status: str
    quality_flag: str

    @property
    def propagated_exposure(self) -> Decimal:
        return self.total_requirement_exposure - self.direct_exposure

    @property
    def key(self) -> tuple[str, str]:
        return (self.industry_id, self.channel)

    def coefficient(self, basis: str) -> Decimal:
        if basis == "direct":
            return self.direct_exposure
        if basis == "total_requirement":
            return self.total_requirement_exposure
        raise ArtifactIntegrityError(
            f"internal: unknown basis {basis!r} reached coefficient selection"
        )


@dataclass(frozen=True)
class ArtifactBundle:
    """Every verified artifact, keyed for the calculation engine."""

    declarations: tuple[ArtifactDeclaration, ...]
    industries: tuple[Industry, ...]
    pairs: tuple[ExposurePair, ...]
    mediators: tuple[Mediator, ...]
    price_stages: tuple[PriceStage, ...]
    channel_sectors: dict
    structural_reference_year: int

    @property
    def industry_ids(self) -> tuple[str, ...]:
        return tuple(industry.industry_id for industry in self.industries)

    @property
    def industry_names(self) -> dict:
        return {industry.industry_id: industry.name_en for industry in self.industries}

    def pair(self, industry_id: str, channel: str) -> ExposurePair | None:
        for entry in self.pairs:
            if entry.industry_id == industry_id and entry.channel == channel:
                return entry
        return None

    def mediators_for(self, industry_id: str, channel: str) -> tuple[Mediator, ...]:
        return tuple(
            m for m in self.mediators if m.industry_id == industry_id and m.channel == channel
        )

    def price_stage_for(self, industry_id: str, channel: str) -> PriceStage | None:
        for entry in self.price_stages:
            if entry.industry_id == industry_id and entry.channel == channel:
                return entry
        return None

    def digest_of(self, name: str) -> str:
        for declaration in self.declarations:
            if declaration.name == name:
                return declaration.sha256
        raise ArtifactIntegrityError(f"no artifact named {name!r}")


# ---------------------------------------------------------------------------
# Declarations
# ---------------------------------------------------------------------------


def read_artifact_declarations(policy_path: Path | str | None = None) -> tuple:
    """Read and validate the four artifact declarations from the policy file.

    Refuses a declaration set that is the wrong size, names an unexpected artifact,
    repeats a logical name, repeats a path, omits a required field, or names a digest
    representation this module does not implement.
    """
    raw = _policy_mapping(policy_path)
    entries = raw.get("runtime_artifacts")
    if not isinstance(entries, list):
        raise ScenarioPolicyError("policy: runtime_artifacts must be a list of declarations")
    if raw.get("runtime_artifacts_are_a_closed_set") is not True:
        raise ScenarioPolicyError("policy: runtime_artifacts_are_a_closed_set must be true")
    if raw.get("runtime_artifacts_discovered_by_scan") is not False:
        raise ScenarioPolicyError("policy: runtime_artifacts_discovered_by_scan must be false")
    if raw.get("runtime_artifacts_fall_back_to_unpinned") is not False:
        raise ScenarioPolicyError("policy: runtime_artifacts_fall_back_to_unpinned must be false")
    if raw.get("historical_release_manifest_is_a_runtime_registry") is not False:
        raise ScenarioPolicyError(
            "policy: historical_release_manifest_is_a_runtime_registry must be false — a frozen "
            "publication record is not a live artifact registry"
        )

    declarations: list[ArtifactDeclaration] = []
    seen_names: set[str] = set()
    seen_paths: set[str] = set()
    for index, entry in enumerate(entries):
        at = f"policy:runtime_artifacts[{index}]"
        if not isinstance(entry, dict):
            raise ScenarioPolicyError(f"{at}: each declaration must be a mapping")
        name = _required_text(entry, "name", where=at)
        path = _required_text(entry, "path", where=at)
        fmt = _required_text(entry, "format", where=at)
        sha = _required_text(entry, "sha256", where=at)
        representation = _required_text(entry, "digest_representation", where=at)
        if name not in ARTIFACT_NAMES:
            raise ScenarioPolicyError(
                f"{at}: {name!r} is not a runtime artifact of this release; expected one of "
                f"{list(ARTIFACT_NAMES)}"
            )
        if name in seen_names:
            raise ScenarioPolicyError(f"{at}: duplicate logical artifact name {name!r}")
        if path in seen_paths:
            raise ScenarioPolicyError(f"{at}: duplicate artifact path {path!r}")
        if representation not in SUPPORTED_DIGEST_REPRESENTATIONS:
            raise ScenarioPolicyError(
                f"{at}: digest_representation {representation!r} is not implemented; a pin whose "
                f"representation is unknown verifies nothing. Expected one of "
                f"{sorted(SUPPORTED_DIGEST_REPRESENTATIONS)}"
            )
        if fmt not in ("json", "csv"):
            raise ScenarioPolicyError(f"{at}: format {fmt!r} is not json or csv")
        if len(sha) != 64 or any(c not in "0123456789abcdef" for c in sha):
            raise ScenarioPolicyError(f"{at}: sha256 {sha!r} is not 64 lower-case hex characters")
        seen_names.add(name)
        seen_paths.add(path)
        declarations.append(
            ArtifactDeclaration(
                name=name, path=path, fmt=fmt, sha256=sha,
                digest_representation=representation,
                role=str(entry.get("role", "")).strip(),
            )
        )
    missing = [name for name in ARTIFACT_NAMES if name not in seen_names]
    if missing:
        raise ScenarioPolicyError(f"policy: runtime artifact declarations missing {missing}")
    return tuple(declarations)


def _policy_mapping(policy_path: Path | str | None):
    """The raw policy mapping, read through the contract module's own policy loader."""
    path = Path(policy_path) if policy_path is not None else DEFAULT_POLICY_PATH
    if not path.is_file():
        raise ScenarioPolicyError(f"scenario policy configuration not found: {path}")
    try:
        raw = yaml.load(path.read_text(encoding="utf-8"), Loader=_PolicyLoader)
    except Exception as exc:  # noqa: BLE001 - any parse failure is one policy defect
        raise ScenarioPolicyError(f"{path}: policy could not be parsed: {exc}") from exc
    if not isinstance(raw, dict):
        raise ScenarioPolicyError(f"{path}: policy must be a mapping")
    return raw


def _required_text(mapping: dict, key: str, *, where: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ScenarioPolicyError(f"{where}: {key!r} must be a non-empty string")
    return value.strip()


# ---------------------------------------------------------------------------
# Path safety
# ---------------------------------------------------------------------------


def _resolve_within(root: Path, relative: str, *, name: str) -> Path:
    """Resolve a declared artifact path, refusing every way out of the root.

    Spelling is checked first so the message names the rule that was broken, and
    resolution is checked afterwards because spelling is not what decides where a
    path lands: a symbolic link can be entirely well-behaved on paper.
    """
    if not relative:
        raise ArtifactIntegrityError(f"{name}: artifact path is empty")
    candidate = Path(relative)
    if candidate.is_absolute():
        raise ArtifactIntegrityError(f"{name}: artifact path {relative!r} is absolute")
    if candidate.drive or relative[1:2] == ":":
        raise ArtifactIntegrityError(f"{name}: artifact path {relative!r} is drive-qualified")
    if relative.startswith(("/", "\\")):
        raise ArtifactIntegrityError(
            f"{name}: artifact path {relative!r} starts with a separator, so it is not relative "
            "to the repository root"
        )
    if ".." in candidate.parts:
        raise ArtifactIntegrityError(
            f"{name}: artifact path {relative!r} contains '..' and could leave the repository"
        )
    root_real = Path(root).resolve()
    resolved = (root_real / candidate).resolve()
    if not resolved.is_relative_to(root_real):
        raise ArtifactIntegrityError(
            f"{name}: artifact path {relative!r} resolves to {resolved}, outside the repository "
            f"root {root_real}"
        )
    return resolved


def _verified_bytes(root: Path, declaration: ArtifactDeclaration) -> bytes:
    path = _resolve_within(root, declaration.path, name=declaration.name)
    if not path.exists():
        raise ArtifactIntegrityError(
            f"{declaration.name}: pinned artifact {declaration.path} is missing. It is never "
            "regenerated and there is no unpinned fallback"
        )
    if not path.is_file():
        raise ArtifactIntegrityError(f"{declaration.name}: {declaration.path} is not a file")
    data = path.read_bytes()
    actual = declaration.digest_of(data)
    if actual != declaration.sha256:
        raise ArtifactIntegrityError(
            f"{declaration.name}: {declaration.path} does not match its pin. Expected "
            f"{declaration.sha256} ({declaration.digest_representation}), measured {actual}. The "
            "artifact is not repaired and the calculation does not proceed"
        )
    return data


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _json_document(data: bytes, declaration: ArtifactDeclaration) -> dict:
    """Parse a pinned JSON artifact with every number as an exact decimal."""
    try:
        loaded = json.loads(data.decode("utf-8"), parse_float=Decimal, parse_constant=Decimal)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ArtifactIntegrityError(
            f"{declaration.name}: {declaration.path} is not valid UTF-8 JSON: {exc}"
        ) from exc
    if not isinstance(loaded, dict):
        raise ArtifactIntegrityError(
            f"{declaration.name}: {declaration.path} must be a JSON object"
        )
    return loaded


def _rows(document: dict, key: str, declaration: ArtifactDeclaration) -> list:
    rows = document.get(key)
    if not isinstance(rows, list) or not rows:
        raise ArtifactIntegrityError(
            f"{declaration.name}: {declaration.path} has no non-empty {key!r} array"
        )
    for index, row in enumerate(rows):
        if not isinstance(row, dict):
            raise ArtifactIntegrityError(
                f"{declaration.name}: {key}[{index}] is not an object"
            )
    return rows


def _decimal(row: dict, key: str, *, where: str, allow_null: bool = False) -> Decimal | None:
    value = row.get(key, "__missing__")
    if value == "__missing__":
        raise ArtifactIntegrityError(f"{where}: required field {key!r} is missing")
    if value is None:
        if allow_null:
            return None
        raise ArtifactIntegrityError(f"{where}: {key!r} is null where a number is required")
    if isinstance(value, bool) or not isinstance(value, (int, Decimal)):
        raise ArtifactIntegrityError(
            f"{where}: {key!r} must be a number, got {type(value).__name__}. A float here would "
            "mean the artifact was parsed without exact decimals"
        )
    result = value if isinstance(value, Decimal) else Decimal(value)
    if not result.is_finite():
        raise ArtifactIntegrityError(f"{where}: {key!r} is not finite")
    return result


def _text_field(row: dict, key: str, *, where: str, allow_null: bool = False) -> str | None:
    value = row.get(key, "__missing__")
    if value == "__missing__":
        raise ArtifactIntegrityError(f"{where}: required field {key!r} is missing")
    if value is None:
        if allow_null:
            return None
        raise ArtifactIntegrityError(f"{where}: {key!r} is null where text is required")
    if not isinstance(value, str):
        raise ArtifactIntegrityError(f"{where}: {key!r} must be text, got {type(value).__name__}")
    return value


def _industries(data: bytes, declaration: ArtifactDeclaration) -> tuple:
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ArtifactIntegrityError(
            f"{declaration.name}: {declaration.path} is not valid UTF-8"
        ) from exc
    reader = csv.DictReader(io.StringIO(text, newline=""))
    expected = ["industry_id", "name_en", "name_th", "tsic_divisions", "status", "source_of_truth"]
    if reader.fieldnames != expected:
        raise ArtifactIntegrityError(
            f"{declaration.name}: {declaration.path} columns are {reader.fieldnames}, expected "
            f"{expected}"
        )
    industries = []
    seen = set()
    for index, row in enumerate(reader):
        at = f"{declaration.name}:row[{index}]"
        industry_id = (row.get("industry_id") or "").strip()
        name_en = (row.get("name_en") or "").strip()
        if not industry_id or not name_en:
            raise ArtifactIntegrityError(f"{at}: industry_id and name_en are required")
        if industry_id in seen:
            raise ArtifactIntegrityError(f"{at}: duplicate industry_id {industry_id!r}")
        seen.add(industry_id)
        industries.append(
            Industry(
                industry_id=industry_id,
                name_en=name_en,
                tsic_divisions=tuple(
                    part for part in (row.get("tsic_divisions") or "").split(";") if part
                ),
                status=(row.get("status") or "").strip(),
            )
        )
    if len(industries) != EXPECTED_INDUSTRY_COUNT:
        raise ArtifactIntegrityError(
            f"{declaration.name}: expected {EXPECTED_INDUSTRY_COUNT} industries, found "
            f"{len(industries)}"
        )
    return tuple(sorted(industries, key=lambda item: item.industry_id))


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def load_artifact_bundle(root: Path | str, *, policy: ScenarioPolicy | None = None,
                         policy_path: Path | str | None = None) -> ArtifactBundle:
    """Verify and load the four pinned artifacts beneath ``root``.

    ``root`` is explicit so a test can point the loader at a temporary tree without the
    module guessing anything. Every artifact is digest-checked before it is parsed, and
    the parsed dataset is then checked against the policy and against itself.
    """
    root_path = Path(root)
    if not root_path.is_dir():
        raise ArtifactIntegrityError(f"repository root {root} is not a directory")
    declarations = read_artifact_declarations(policy_path)
    policy = policy or load_policy(policy_path)
    payloads = {d.name: _verified_bytes(root_path, d) for d in declarations}
    by_name = {d.name: d for d in declarations}

    industries = _industries(payloads["industry_map"], by_name["industry_map"])
    industry_ids = {industry.industry_id for industry in industries}
    industry_names = {i.industry_id: i.name_en for i in industries}

    channel_sectors = {entry.channel: entry.io_sector_code for entry in policy.channels}
    if set(channel_sectors) != set(REGISTERED_CHANNELS):
        raise ArtifactIntegrityError(
            f"policy channels {sorted(channel_sectors)} are not the registered set "
            f"{sorted(REGISTERED_CHANNELS)}"
        )

    pairs = _exposure_pairs(payloads, by_name, industry_ids, industry_names, channel_sectors)
    mediators = _mediators(payloads, by_name, {p.key for p in pairs})
    price_stages = _price_stages(payloads, by_name, {p.key for p in pairs})
    _cross_check(pairs, mediators, price_stages, policy_path)

    reference_year = policy.structural_reference_year
    return ArtifactBundle(
        declarations=declarations,
        industries=industries,
        pairs=pairs,
        mediators=mediators,
        price_stages=price_stages,
        channel_sectors=dict(sorted(channel_sectors.items())),
        structural_reference_year=reference_year,
    )


def _exposure_pairs(payloads, by_name, industry_ids, industry_names, channel_sectors) -> tuple:
    declaration = by_name["exposure_matrix"]
    document = _json_document(payloads["exposure_matrix"], declaration)
    rows = _rows(document, "canonical_rows", declaration)
    if len(rows) != EXPECTED_PAIR_COUNT:
        raise ArtifactIntegrityError(
            f"{declaration.name}: expected {EXPECTED_PAIR_COUNT} canonical rows, found {len(rows)}"
        )
    crosswalk = document.get("commodity_crosswalk")
    if not isinstance(crosswalk, dict):
        raise ArtifactIntegrityError(f"{declaration.name}: commodity_crosswalk is missing")

    pairs = []
    seen = set()
    for index, row in enumerate(rows):
        at = f"{declaration.name}:canonical_rows[{index}]"
        industry_id = _text_field(row, "industry_id", where=at)
        channel = _text_field(row, "commodity_series_id", where=at)
        if industry_id not in industry_ids:
            raise ArtifactIntegrityError(f"{at}: unexpected industry {industry_id!r}")
        if channel not in channel_sectors:
            raise ArtifactIntegrityError(f"{at}: unexpected channel {channel!r}")
        key = (industry_id, channel)
        if key in seen:
            raise ArtifactIntegrityError(f"{at}: duplicate industry/channel pair {key}")
        seen.add(key)
        sector = _text_field(row, "commodity_io_sector_code", where=at)
        if sector != channel_sectors[channel]:
            raise ArtifactIntegrityError(
                f"{at}: channel {channel!r} maps to sector {sector!r} here and to "
                f"{channel_sectors[channel]!r} in the policy"
            )
        declared_sector = crosswalk.get(channel, {}).get("io_sector_code")
        if declared_sector != sector:
            raise ArtifactIntegrityError(
                f"{at}: crosswalk sector {declared_sector!r} disagrees with row sector {sector!r}"
            )
        name = _text_field(row, "industry_name", where=at)
        if name != industry_names[industry_id]:
            raise ArtifactIntegrityError(
                f"{at}: industry name {name!r} disagrees with the industry map "
                f"({industry_names[industry_id]!r})"
            )
        direct = _decimal(row, "direct_exposure", where=at)
        total = _decimal(row, "total_requirement_exposure", where=at)
        published_indirect = _decimal(row, "indirect_exposure", where=at)
        if direct < 0 or total < 0:
            raise ArtifactIntegrityError(f"{at}: exposures must be non-negative")
        if total < direct:
            raise ArtifactIntegrityError(
                f"{at}: total requirement {total} is below direct {direct}, so the propagated "
                "component would be negative"
            )
        sign = row.get("price_increase_to_stress_sign")
        if sign is not None and sign not in (1, -1):
            raise ArtifactIntegrityError(f"{at}: sign {sign!r} is neither null, 1 nor -1")
        eligible = row.get("industry_pair_feature_eligible")
        if not isinstance(eligible, bool):
            raise ArtifactIntegrityError(f"{at}: industry_pair_feature_eligible must be boolean")
        channel_kind = _text_field(row, "direction_channel", where=at)
        if sign is None and eligible:
            raise ArtifactIntegrityError(
                f"{at}: the pair is eligible but its direction sign is null, which cannot both "
                "be true"
            )
        if channel_kind == "mixed_or_ambiguous" and sign is not None:
            raise ArtifactIntegrityError(
                f"{at}: direction channel is mixed_or_ambiguous but a sign is published"
            )
        pairs.append(
            ExposurePair(
                industry_id=industry_id,
                industry_name=name,
                channel=channel,
                io_sector_code=sector,
                direct_exposure=direct,
                total_requirement_exposure=total,
                published_indirect_exposure=published_indirect,
                sign=sign,
                direction_channel=channel_kind,
                feature_eligible=eligible,
                proxy_fit_status=_text_field(row, "commodity_proxy_fit_status", where=at),
                quality_flag=_text_field(row, "quality_flag", where=at),
            )
        )
    expected_keys = {(i, c) for i in industry_ids for c in channel_sectors}
    if seen != expected_keys:
        raise ArtifactIntegrityError(
            f"{declaration.name}: pair coverage is incomplete; missing "
            f"{sorted(expected_keys - seen)}"
        )
    return tuple(sorted(pairs, key=lambda p: (p.industry_id, p.channel)))


def _mediators(payloads, by_name, pair_keys) -> tuple:
    declaration = by_name["structural_path_audit"]
    document = _json_document(payloads["structural_path_audit"], declaration)
    rows = _rows(document, "mediator_table", declaration)
    expected_total = EXPECTED_PAIR_COUNT * EXPECTED_MEDIATORS_PER_PAIR
    if len(rows) != expected_total:
        raise ArtifactIntegrityError(
            f"{declaration.name}: expected {expected_total} mediator rows, found {len(rows)}"
        )
    mediators = []
    identities = set()
    per_pair: dict = {}
    for index, row in enumerate(rows):
        at = f"{declaration.name}:mediator_table[{index}]"
        industry_id = _text_field(row, "industry_id", where=at)
        channel = _text_field(row, "commodity_series_id", where=at)
        key = (industry_id, channel)
        if key not in pair_keys:
            raise ArtifactIntegrityError(f"{at}: mediator names an unknown pair {key}")
        rank = row.get("rank")
        if not isinstance(rank, int) or isinstance(rank, bool) or not 1 <= rank <= (
            EXPECTED_MEDIATORS_PER_PAIR
        ):
            raise ArtifactIntegrityError(
                f"{at}: rank {rank!r} is not an integer in 1..{EXPECTED_MEDIATORS_PER_PAIR}"
            )
        identity = (industry_id, channel, rank)
        if identity in identities:
            raise ArtifactIntegrityError(f"{at}: duplicate mediator identity {identity}")
        identities.add(identity)
        per_pair[key] = per_pair.get(key, 0) + 1
        mediators.append(
            Mediator(
                industry_id=industry_id,
                channel=channel,
                rank=rank,
                intermediate_sector_code=_text_field(row, "intermediate_sector_code", where=at),
                intermediate_sector_label=_text_field(row, "intermediate_sector_label", where=at),
                contribution=_decimal(row, "indirect_via_sector", where=at),
                share_of_indirect=_decimal(row, "share_of_indirect", where=at),
                cumulative_share=_decimal(row, "cumulative_share", where=at),
                pair_direct_exposure=_decimal(row, "direct_exposure", where=at),
                pair_total_exposure=_decimal(row, "total_exposure", where=at),
            )
        )
    wrong = {k: v for k, v in per_pair.items() if v != EXPECTED_MEDIATORS_PER_PAIR}
    if wrong or set(per_pair) != pair_keys:
        raise ArtifactIntegrityError(
            f"{declaration.name}: every pair needs exactly {EXPECTED_MEDIATORS_PER_PAIR} "
            f"mediators; offending {sorted(wrong) or sorted(pair_keys - set(per_pair))}"
        )
    return tuple(sorted(mediators, key=lambda m: (m.industry_id, m.channel, m.rank)))


def _price_stages(payloads, by_name, pair_keys) -> tuple:
    declaration = by_name["price_stage_source_audit"]
    document = _json_document(payloads["price_stage_source_audit"], declaration)
    rows = _rows(document, "price_stage_alignment", declaration)
    if len(rows) != EXPECTED_PAIR_COUNT:
        raise ArtifactIntegrityError(
            f"{declaration.name}: expected {EXPECTED_PAIR_COUNT} price-stage records, found "
            f"{len(rows)}"
        )
    stages = []
    seen = set()
    for index, row in enumerate(rows):
        at = f"{declaration.name}:price_stage_alignment[{index}]"
        industry_id = _text_field(row, "industry_id", where=at)
        channel = _text_field(row, "commodity_series_id", where=at)
        key = (industry_id, channel)
        if key not in pair_keys:
            raise ArtifactIntegrityError(f"{at}: price-stage record names an unknown pair {key}")
        if key in seen:
            raise ArtifactIntegrityError(f"{at}: duplicate price-stage record for {key}")
        seen.add(key)
        stages.append(
            PriceStage(
                industry_id=industry_id,
                channel=channel,
                price_stage=_text_field(row, "price_stage", where=at),
                alignment_status=_text_field(row, "alignment_status", where=at),
                mapped_io_sector_code=_text_field(row, "mapped_raw_io_sector", where=at),
                limitations=_text_field(row, "limitations", where=at),
                shared_source_sector_warning=_text_field(
                    row, "shared_source_sector_warning", where=at, allow_null=True
                ),
                pair_direct_exposure=_decimal(row, "direct_exposure", where=at),
                pair_total_exposure=_decimal(row, "total_exposure", where=at),
            )
        )
    if seen != pair_keys:
        raise ArtifactIntegrityError(
            f"{declaration.name}: price-stage coverage is incomplete; missing "
            f"{sorted(pair_keys - seen)}"
        )
    return tuple(sorted(stages, key=lambda s: (s.industry_id, s.channel)))


def _cross_check(pairs, mediators, price_stages, policy_path) -> None:
    """C5's own coefficients must agree with C3's within the declared tolerance."""
    raw = _policy_mapping(policy_path)
    agreement = raw.get("cross_artifact_agreement")
    if not isinstance(agreement, dict):
        raise ScenarioPolicyError("policy: cross_artifact_agreement is missing")
    if agreement.get("authoritative_coefficient_source") != "exposure_matrix":
        raise ScenarioPolicyError(
            "policy: the exposure matrix must be the authoritative coefficient source"
        )
    if agreement.get("supporting_artifacts_are_scored") is not False:
        raise ScenarioPolicyError("policy: supporting_artifacts_are_scored must be false")
    if agreement.get("tolerance_is_a_learned_threshold") is not False:
        raise ScenarioPolicyError(
            "policy: tolerance_is_a_learned_threshold must be false — this bound is declared "
            "validation policy and presenting it as estimated would be a false claim"
        )
    tolerance = agreement.get("coefficient_agreement_tolerance")
    if isinstance(tolerance, bool) or not isinstance(tolerance, (int, Decimal)):
        raise ScenarioPolicyError("policy: coefficient_agreement_tolerance must be a number")
    tolerance = Decimal(tolerance)
    if tolerance <= 0:
        raise ScenarioPolicyError("policy: coefficient_agreement_tolerance must be positive")

    by_key = {pair.key: pair for pair in pairs}
    first_mediator = {}
    for mediator in mediators:
        first_mediator.setdefault((mediator.industry_id, mediator.channel), mediator)

    def compare(label, key, left, right):
        difference = abs(left - right)
        if difference > tolerance:
            raise ArtifactIntegrityError(
                f"{key[0]}/{key[1]}: {label} disagrees between the exposure matrix ({left}) and "
                f"the supporting artifact ({right}); the difference {difference} exceeds the "
                f"declared agreement tolerance {tolerance}"
            )

    for key, pair in by_key.items():
        mediator = first_mediator.get(key)
        if mediator is None:
            raise ArtifactIntegrityError(f"{key}: no mediator rows for a published pair")
        compare("mediator direct exposure", key, pair.direct_exposure,
                mediator.pair_direct_exposure)
        compare("mediator total exposure", key, pair.total_requirement_exposure,
                mediator.pair_total_exposure)
    for stage in price_stages:
        key = (stage.industry_id, stage.channel)
        pair = by_key[key]
        if stage.mapped_io_sector_code != pair.io_sector_code:
            raise ArtifactIntegrityError(
                f"{stage.industry_id}/{stage.channel}: price-stage sector "
                f"{stage.mapped_io_sector_code!r} disagrees with the exposure matrix "
                f"({pair.io_sector_code!r})"
            )
        compare("price-stage direct exposure", key, pair.direct_exposure,
                stage.pair_direct_exposure)
        compare("price-stage total exposure", key, pair.total_requirement_exposure,
                stage.pair_total_exposure)
